# Generated by Django 3.0.1 on 2020-07-23 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('date_crated', models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 23, 23, 15, 38, 565889))),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_crated', models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 23, 23, 15, 38, 565889))),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered ', ' ')], max_length=200)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, choices=[('indoor', 'indoor'), ('outdoor', 'outdoor')], max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True, max_length=400)),
                ('date_crated', models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 23, 23, 15, 38, 565889))),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
