# Generated by Django 3.0.1 on 2020-07-24 10:33

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200724_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_crated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 24, 11, 33, 11, 834641)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_crated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 24, 11, 33, 11, 834641)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_crated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 24, 11, 33, 11, 834641)),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
