# Generated by Django 3.0.1 on 2020-07-24 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200724_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_crated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 24, 11, 34, 34, 705686)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_crated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 24, 11, 34, 34, 705686)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_crated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 24, 11, 34, 34, 705686)),
        ),
    ]
