# Generated by Django 3.0.1 on 2020-07-24 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200724_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_crated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 24, 17, 39, 42, 802220)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_crated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 24, 17, 39, 42, 802220)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_crated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 24, 17, 39, 42, 802220)),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='accounts.Tag'),
        ),
    ]
